### ISSUE TITLE
Proposal to include TIP-388 in GreatVoyage-v4.5

### ISSUE THREAD

**Issue by wubin01** [tronprotocol/pm#22]
https://github.com/tronprotocol/tips/issues/388

## Description
This TIP describes how to optimize light node synchronization logic.

The light node only retains some blocks. If the lowest block of the light node is higher than the head block, the block cannot be synchronized, resulting in the connection interruption.

Make the node quickly find a node that can establish an effective connection, avoid repeatedly connecting invalid nodes, and improve the efficiency of connection establishment.

**Comment by ethan1844** [comment]
Close this issue as it is implemented by [GreatVoyage-v4.5.0](https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.5.0).
