### ISSUE TITLE
Proposal to include TIP-387 in GreatVoyage-v4.6

### ISSUE THREAD

**Issue by ljboy123** [tronprotocol/pm#23]
> [tronprotocol/tips#387](https://github.com/tronprotocol/tips/issues/387)
> 
> ## Description
> This TIP describes transaction memo burn trx.

**Comment by ethan1844** [comment]
Added to the v4.5 plan

**Comment by ethan1844** [comment]
Needs more discussion, and will be implemented in versions after GreatVoyage-v4.5.0.

**Comment by ethan1844** [comment]
Close this issue as it is implemented by [GreatVoyage-v4.6.0](https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.6.0).
