### ISSUE TITLE
Proposal to include TIP-391 in GreatVoyage-v4.5

### ISSUE THREAD

**Issue by Vikingzzu** [tronprotocol/pm#24]
https://github.com/tronprotocol/tips/issues/391

Description
This TIP optimize fetch block process between nodes.

Network fluctuations between nodes can cause block fetch timeouts, use a new strategy to prevent such scenarios from occurring.

**Comment by ethan1844** [comment]
Close this issue as it is implemented by [GreatVoyage-v4.5.0](https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.5.0).
