### ISSUE TITLE
Proposal to include TIP-461 in GreatVoyage-v4.6

### ISSUE THREAD

**Issue by guoquanwu** [tronprotocol/pm#28]
> [tronprotocol/tips#461](https://github.com/tronprotocol/tips/issues/461)
> 
> ## Description
> This TIP describes how to optimize database inconsistent when the system shutdown ungracefully.

**Comment by ethan1844** [comment]
Close this issue as it is implemented by [GreatVoyage-v4.6.0](https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.6.0).
