### ISSUE TITLE
Proposal to include TIP-465  in GreatVoyage-v4.6

### ISSUE THREAD

**Issue by bladehan1** [tronprotocol/pm#29]
>[tronprotocol/tips#465](https://github.com/tronprotocol/tips/issues/465)
>
>Description
>---
>This TIP describes new reward calculation algorithm.

**Comment by ethan1844** [comment]
Close this issue as it is implemented by [GreatVoyage-v4.6.0](https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.6.0).
