### ISSUE TITLE
Proposal to include TIP-476 in GreatVoyage-v4.6

### ISSUE THREAD

**Issue by lxcmyf** [tronprotocol/pm#35]
https://github.com/tronprotocol/tips/issues/476
# Description
This TIP describes how to optimize the account index storage structure of resource delegating, to improve transaction execution performance and throughput.

**Comment by ethan1844** [comment]
Close this issue as it is implemented by [GreatVoyage-v4.6.0](https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.6.0).
