### ISSUE TITLE
Proposal to include TIP-542 in GreatVoyage-v4.7.2

### ISSUE THREAD

**Issue by tronenergymarket** [tronprotocol/pm#59]
https://github.com/tronprotocol/tips/issues/542

# Description

This TIP is designed to add a `lock_period `parameter in the `wallet/delegateresource` API in Stake 2.0, to support delegating bandwidth or energy resource with a specified lockup time.

**Comment by vivian-kang** [comment]
Added to [Periander](https://github.com/tronprotocol/pm/issues/42)
