### ISSUE TITLE
Can we add active/passive nodes by calling a specific api?

### ISSUE THREAD

**Issue by KaiQiu9527** [tronprotocol/pm#65]
Hi all, due to the feature in v4.7.2 (https://github.com/tronprotocol/java-tron/pull/5090), we can dynamically add active/passive nodes by modifying the config file. However, we run the java-tron progress in a k8s docker environment, and the config file inside the docker  is mounted by k8s configmap, which only take effects by restarting the pod.

Is it possible to add some active/passive nodes by calling a specific api? Or make a "bootnode" like Ethereum?

Thanks!

**Comment by jwrct** [comment]
@KaiQiu9527 Thank you very much. Your suggestions will be carefully considered, and we will discuss reasonable solutions. Please look forward to future versions.
